[tools]
starship = "latest"
eza = "latest"
bat = "latest"
fzf = "latest"
zoxide = "latest"
yazi = "latest"
direnv = "latest"
neovim = "latest"
"aqua:iffse/pay-respects" = "latest"
btop = "latest"
fastfetch = "latest"
fd = "latest"
zellij = "latest"