---
  - name: "{{ user }} apps and utils"
    apt: name={{ item }}
    become: yes
    with_items:
      - apt-transport-https
      - zsh
      - git
      - nano
      - xstow
      - tmux
      - htop

  - name: "{{ user }} gui apps and utils"
    apt: name={{ item }}
    become: yes
    with_items:
      - feh

  - name: Add nodejs repo key
    become: yes
    apt_key: 
      url=http://ags131repo.s3-website-us-east-1.amazonaws.com/repo.ags131.com.gpg.key
      state=present

  - name: Add nodejs repo
    become: yes
    apt_repository:
      repo: 'deb https://s3.amazonaws.com/ags131repo/debian main main'
      state: present
      update_cache: yes

  - name: Clone oh-my-zsh repo
    git: 
      repo: https://github.com/robbyrussell/oh-my-zsh.git
      dest: /home/{{ user }}/.oh-my-zsh

  - name: Setup {{ user }} shell
    user: name={{ user }}
         comment="Adam Shumann"
         shell=/bin/zsh

  - name: Install git
    apt: name=git update_cache=yes state=latest
    become: yes

  - name: Git clone powerline-shell
    become_user: "{{ user }}"
    git:
      repo: https://github.com/milkbikis/powerline-shell
      dest: /home/{{ user }}/src/powerline-shell

  - name: Copy powerline config
    become_user: "{{ user }}"
    copy:
      src: files/powerline-config.py 
      dest: /home/{{ user }}/src/powerline-shell/config.py

  - name: Execute install
    become_user: "{{ user }}"
    shell: ./install.py
    args:
      chdir: /home/{{ user }}/src/powerline-shell

  - name: Clone dotfiles
    become_user: "{{ user }}"
    git: 
      repo: https://github.com/ags131/dotfiles
      dest: /home/{{ user }}/src/dotfiles
      version: master
      recursive: yes
    tags: dotfiles
    when: debug == false

  - name: Remove existing files
    file: dest=/home/{{ user }}/{{ item }} state=absent
    with_items:
       - .bashrc
       - .bash_logout

  - name: Remove broken links
    become_user: "{{ user }}"
    shell: find -L /home/{{ user }} -maxdepth 1 -xdev -type l -delete
    tags: dotfiles

  - name: Ensure NPM Prefix
    lineinfile:
      create: true
      dest: /home/{{ user }}/.npmrc
      line: 'prefix=/home/{{ user }}/npm-global'
      state: present

  - name: Unstow
    become_user: "{{ user }}"
    shell: cd /home/{{ user }}/src/dotfiles && xstow -t /home/{{ user }} bash zsh git shell tmux jshint i3
    tags: dotfiles

  - name: Setup bin
    become_user: "{{ user }}"
    file:
      path: /home/{{ user }}/bin
      state: directory
