---
 - name: "{{ user }} apps and utils"
   apt: name={{ item }}
   sudo: yes
   with_items:
       - nano
       - xstow

 - name: "{{ user }} gui apps and utils"
   apt: name={{ item }}
   sudo: yes
   with_items:
       - feh

 - name: Add nodejs repo key
   sudo: yes
   apt_key: 
     url=http://repo.ags131.com/repo.ags131.com.gpg.key
     state=present

 - name: Add nodejs repo
   sudo: yes
   apt_repository:
     repo='deb http://repo.ags131.com/debian main main'
     state=present
     update_cache=yes

 - name: Setup {{ user }} shell
   user: name={{ user }}
         comment="Adam Shumann"
         shell=/bin/bash

 - name: Clone dotfiles
   sudo_user: "{{ user }}"
   git: repo=https://github.com/ags131/dotfiles
     dest=/home/{{ user }}/src/dotfiles
     version=master
     recursive=yes
   tags: dotfiles

 - name: Remove existing files
   file: dest=/home/{{ user }}/{{ item }} state=absent
   with_items:
       - .bashrc
       - .bash_logout

 - name: Remove broken links
   sudo_user: "{{ user }}"
   shell: find -L /home/{{ user }} -type l -delete
   tags: dotfiles

 - name: Unstow
   sudo_user: "{{ user }}"
   shell: cd /home/{{ user }}/src/dotfiles && xstow -t /home/{{ user }} bash git shell tmux jshint npm sublime
   tags: dotfiles
