---
 - name: "{{ user }} apps and utils"
   apt: name={{ item }}
   become: yes
   with_items:
       - apt-transport-https
       - zsh
       - git
       - nano
       - xstow
       - tmux
       - htop

 - name: "{{ user }} gui apps and utils"
   apt: name={{ item }}
   become: yes
   with_items:
       - feh

 - name: Add nodejs repo key
   become: yes
   apt_key: 
     url=http://ags131repo.s3-website-us-east-1.amazonaws.com/repo.ags131.com.gpg.key
     state=present

 - name: Add nodejs repo
   become: yes
   apt_repository:
     repo='deb https://s3.amazonaws.com/ags131repo/debian main main'
     state=present
     update_cache=yes

 - name: Setup {{ user }} shell
   user: name={{ user }}
         comment="Adam Shumann"
         shell=/bin/zsh

 - name: Clone dotfiles
   become_user: "{{ user }}"
   git: repo=https://github.com/ags131/dotfiles
     dest=/home/{{ user }}/src/dotfiles
     version=master
     recursive=yes
   tags: dotfiles
   when: debug == false

 - name: Remove existing files
   file: dest=/home/{{ user }}/{{ item }} state=absent
   with_items:
       - .bashrc
       - .bash_logout

 - name: Remove broken links
   become_user: "{{ user }}"
   shell: find -L /home/{{ user }} -maxdepth 1 -xdev -type l -delete
   tags: dotfiles

 - name: Unstow
   become_user: "{{ user }}"
   shell: cd /home/{{ user }}/src/dotfiles && xstow -t /home/{{ user }} bash zsh git shell tmux jshint npm i3
   tags: dotfiles

 - name: Setup bin
   file:
    path: /home/{{ user }}/bin
    state: directory

 - name: Unstow bin
   become_user: "{{ user }}"
   shell: cd /home/{{ user }}/src/dotfiles && xstow -t /home/{{ user }}/bin bin
   tags: dotfiles
