#!/usr/bin/env bash

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "dotfiles:alinanova21/dotfiles"

cd "$HOME"
echo "Init submodules"
yadm submodule update --recursive --init

mkdir -p ~/.ssh

if ! grep 'Host dotfiles' ~/.ssh/config ; then
  cat - << EOF >> ~/.ssh/config
Host dotfiles
  Hostname github.com
  User git
  IdentityFile ~/.ssh/dotfiles
EOF
fi

echo "Decrypt files"
yadm decrypt