#!/usr/bin/env bash
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
sudo chsh -s /usr/bin/zsh

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:ags131/dotfiles"

cd "$HOME"
echo "Init submodules"
yadm submodule update --recursive --init

grep 'Host dotfiles' ~/.ssh/config
if ! $? ; then
  cat - << EOF >> ~/.ssh/config
Host dotfiles
  Hostname github.com
  User git
  IdentityFile ~/.ssh/dotfiles
EOF
fi