[wallpaper.default]
path = "/home/alina/.config/noctalia/assets/wallhaven-3k6l1v.png"

[wallpaper.last]
path = "/home/alina/.config/noctalia/assets/wallhaven-3k6l1v.png"

[wallpaper.monitors.DP-1]
path = "/home/alina/.config/noctalia/assets/wallhaven-3k6l1v.png"

[wallpaper.monitors.DP-2]
path = "/home/alina/.config/noctalia/assets/wallhaven-3k6l1v.png"

[wallpaper.monitors.DP-3]
path = "/home/alina/.config/noctalia/assets/wallhaven-3k6l1v.png"